diff --git a/kernel/linux-asic/drivers/staging/Makefile b/kernel/linux-asic/drivers/staging/Makefile
index 4e2f479..31b8715 100644
--- a/kernel/linux-asic/drivers/staging/Makefile
+++ b/kernel/linux-asic/drivers/staging/Makefile
@@ -42,4 +42,5 @@ obj-$(CONFIG_ISDN_I4L)		+= i4l/
 obj-$(CONFIG_KS7010)		+= ks7010/
 obj-$(CONFIG_GREYBUS)		+= greybus/
 obj-$(CONFIG_BCM2708_VCHIQ)	+= vc04_services/
-obj-$(CONFIG_MTD_SPINAND_W25N)	+= w25n_spinand/
\ No newline at end of file
+obj-$(CONFIG_MTD_SPINAND_W25N)	+= w25n_spinand/
+obj-$(CONFIG_MTD_SPINAND_GD5F2_XX)	+= gd5f2xx_spinand/
